on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-22.04
    concurrency:
      group: ${{ github.workflow }}
      cancel-in-progress: true
    
    steps:
      - name: SSH Test
        run: |
          echo "${{ secrets.SSH_DEPLOY_KEY }}" > deploy.pem
          chmod 400 deploy.pem
          ssh -o StrictHostKeyChecking=no -i deploy.pem ec2-user@llemonduck.dev echo hi
        
      - uses: actions/checkout@v4
        with:
          lfs: true

      - uses: actions/cache@v3
        with:
          path: Library
          key: Library-${{ hashFiles('Assets/**', 'Packages/**', 'ProjectSettings/**') }}
          restore-keys: |
            Library-

      - uses: game-ci/unity-builder@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          targetPlatform: 'WebGL'
          unityVersion: '2022.3.42f1'

      - uses: actions/upload-artifact@v3
        with:
          name: WebGL Build
          path: build

      - name: Deploy to Host
        run: |
          tar czvf build.tar.gz ./build
          echo "${{ secrets.SSH_DEPLOY_KEY }}" > deploy.pem
          chmod 400 deploy.pem
          scp -o StrictHostKeyChecking=no -i deploy.pem -r ./build.tar.gz ec2-user@llemonduck.dev:
          ssh -o StrictHostKeyChecking=no -i deploy.pem ec2-user@llemonduck.dev ./deploy.sh
